### ISSUE TITLE
Errors on converting NDPI (Hamamatsu) WSI

### ISSUE THREAD

**Issue by gvincke** [imi-bigpicture/wsidicomizer#21]
File used : https://cytomine.com/collection/cmu-1/cmu-1-ndpi
Command used : `wsidicomizer -i /tmp/CMU-1.ndpi -o /tmp/CMU-1-ndpi`
Result : 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/opentile/jpeg.py", line 226, in crop_multiple
    return self._turbo_jpeg.crop_multiple(frame, crop_parameters)
  File "/usr/local/lib/python3.8/dist-packages/turbojpeg.py", line 670, in crop_multiple
    self.__report_error(handle)
  File "/usr/local/lib/python3.8/dist-packages/turbojpeg.py", line 882, in __report_error
    raise IOError(self.__get_error_string(handle))
OSError: Invalid crop request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/opentile/ndpi_tiler.py", line 619, in _crop_to_tiles
    tiles: List[bytes] = self._jpeg.crop_multiple(
  File "/usr/local/lib/python3.8/dist-packages/opentile/jpeg.py", line 228, in crop_multiple
    raise JpegCropError(
opentile.jpeg.JpegCropError: Crop of frame failed with parameters [(0, 0, 512, 512), (512, 0, 512, 512), (1024, 0, 512, 512), (1536, 0, 512, 512)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wsidicomizer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/wsidicomizer/cli.py", line 134, in main
    WsiDicomizer.convert(
  File "/usr/local/lib/python3.8/dist-packages/wsidicomizer/interface.py", line 185, in convert
    created_files = wsi.save(
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/wsidicom.py", line 1964, in save
    collection_filepaths = collection.save(
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/wsidicom.py", line 1089, in save
    group_file_paths = group.save(
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/wsidicom.py", line 591, in save
    wsi_file.write(
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/instance.py", line 2939, in write
    frame_positions += self._write_pixel_data(
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/instance.py", line 3281, in _write_pixel_data
    for thread_result in pool.map(
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/instance.py", line 3262, in get_tiles_thread
    return image_data.get_encoded_tiles(tile_points, z, path)
  File "/usr/local/lib/python3.8/dist-packages/wsidicomizer/opentile.py", line 207, in get_encoded_tiles
    return self._tiled_page.get_tiles(tiles_tuples)
  File "/usr/local/lib/python3.8/dist-packages/opentile/ndpi_tiler.py", line 543, in get_tiles
    return [
  File "/usr/local/lib/python3.8/dist-packages/opentile/ndpi_tiler.py", line 546, in <listcomp>
    for tile in self._create_tiles(frame_job).values()
  File "/usr/local/lib/python3.8/dist-packages/opentile/ndpi_tiler.py", line 596, in _create_tiles
    tiles = self._crop_to_tiles(frame_job, frame)
  File "/usr/local/lib/python3.8/dist-packages/opentile/ndpi_tiler.py", line 624, in _crop_to_tiles
    raise ValueError(
ValueError: Failed to crop at position 0,74 with parameters [(0, 0, 512, 512), (512, 0, 512, 512), (1024, 0, 512, 512), (1536, 0, 512, 512)].
```
Other tests where done using other NDPI files, and the result is always like that. Never succeeded to convert a NDPI file.
What am i missing .
Thank you.
Grégoire

**Comment by gvincke** [comment]
Other example.
File used : https://cytomine.com/collection/os-1/os-1-ndpi
Command used : `wsidicomizer -i /tmp/OS-1.ndpi -o /tmp/OS-1-ndpi`
Result : 
```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/opentile/jpeg.py", line 226, in crop_multiple
    return self._turbo_jpeg.crop_multiple(frame, crop_parameters)
  File "/usr/local/lib/python3.8/dist-packages/turbojpeg.py", line 670, in crop_multiple
    self.__report_error(handle)
  File "/usr/local/lib/python3.8/dist-packages/turbojpeg.py", line 882, in __report_error
    raise IOError(self.__get_error_string(handle))
OSError: Invalid crop request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/opentile/ndpi_tiler.py", line 619, in _crop_to_tiles
    tiles: List[bytes] = self._jpeg.crop_multiple(
  File "/usr/local/lib/python3.8/dist-packages/opentile/jpeg.py", line 228, in crop_multiple
    raise JpegCropError(
opentile.jpeg.JpegCropError: Crop of frame failed with parameters [(0, 0, 512, 512)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wsidicomizer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/wsidicomizer/cli.py", line 134, in main
    WsiDicomizer.convert(
  File "/usr/local/lib/python3.8/dist-packages/wsidicomizer/interface.py", line 185, in convert
    created_files = wsi.save(
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/wsidicom.py", line 1964, in save
    collection_filepaths = collection.save(
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/wsidicom.py", line 1089, in save
    group_file_paths = group.save(
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/wsidicom.py", line 591, in save
    wsi_file.write(
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/instance.py", line 2939, in write
    frame_positions += self._write_pixel_data(
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/instance.py", line 3281, in _write_pixel_data
    for thread_result in pool.map(
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/wsidicom/instance.py", line 3262, in get_tiles_thread
    return image_data.get_encoded_tiles(tile_points, z, path)
  File "/usr/local/lib/python3.8/dist-packages/wsidicomizer/opentile.py", line 207, in get_encoded_tiles
    return self._tiled_page.get_tiles(tiles_tuples)
  File "/usr/local/lib/python3.8/dist-packages/opentile/ndpi_tiler.py", line 543, in get_tiles
    return [
  File "/usr/local/lib/python3.8/dist-packages/opentile/ndpi_tiler.py", line 546, in <listcomp>
    for tile in self._create_tiles(frame_job).values()
  File "/usr/local/lib/python3.8/dist-packages/opentile/ndpi_tiler.py", line 596, in _create_tiles
    tiles = self._crop_to_tiles(frame_job, frame)
  File "/usr/local/lib/python3.8/dist-packages/opentile/ndpi_tiler.py", line 624, in _crop_to_tiles
    raise ValueError(
ValueError: Failed to crop at position 0,13 with parameters [(0, 0, 512, 512)].
```

**Comment by ap--** [comment]
Hi @gvincke 

Could this be related to: https://github.com/imi-bigpicture/opentile/issues/28 ?

If so, check that you have lib-turbojpeg >= 2.1

**Comment by gvincke** [comment]
@ap-- How can i check that ? (Ubuntu 20.04)

**Comment by gvincke** [comment]
@ap--  I read in the linked issue that in Ubuntu 20.04 it's still <2.0. 
So i tried with a docker image of Ubuntu 22.04 and it works.
Thank you.

**Comment by gvincke** [comment]
@ap-- Thank you. But as for many python tools i prefer to run the wsidicomizer in a docker container, so i just switched my Dockerfile base from`ubuntu:20.04` to `ubuntu:22.04`.
